#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -t 10:00:00
#SBATCH -J Leono_assembly
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se

# Load modules
module load bioinfo-tools
module load canu

# Your commands
cd $SNIC_TMP
canu -p pacbio -d pacbio_assembly_retry genomeSize=25m corThreads=16 useGrid=false -pacbio /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/pacbio_data/SRR6037732_scaffold_10.fq.gz
cp -r pacbio_assembly_retry /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/retry
