#!/bin/bash -l

#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 20:00:00
#SBATCH -J Leono_assembly
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se

# Load modules
module load bioinfo-tools
module load canu

# Your commands
cd $SNIC_TMP
canu -p pacbio -d pacbio_assembly genomeSize=36m useGrid=false corMaxEvidenceErate=0.15 -pacbio /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/pacbio_data/SRR6037732_scaffold_10.fq.gz
cp -r /scratch/$SLURM_JOB_ID/pacbio_assembly /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly
