#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 30:00
#SBATCH -J leono_qualitycontrol
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load FastQC

# Your commands
fastqc -o /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/02_pre_processing/transcriptome_Illumina -t 2 \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/trimmed_data/Illumina_transcriptome_trimmed_1P.fq.gz \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/trimmed_data/Illumina_transcriptome_trimmed_2P.fq.gz
