#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J leono_trimming
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load trimmomatic

# Your commands
java -jar $TRIMMOMATIC_ROOT/trimmomatic.jar PE \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/untrimmed/SRR6040095_scaffold_10.1.fastq.gz \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/untrimmed/SRR6040095_scaffold_10.2.fastq.gz\
 -baseout Illumina_transcriptome_trimmed.fq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

