#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 12:00:00
#SBATCH -J leono_Pilon
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load samtools
module load Pilon

# Your commands
cd $SNIC_TMP
samtools index -@ 2 /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/mapped_reads/mapped_reads_sorted.bam
java -jar $PILON_HOME/pilon.jar --genome /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/pacbio_assembly/pacbio.contigs.fasta \
--bam /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/mapped_reads/mapped_reads_sorted.bam \
--threads 2 \
--output Corrected_assembly \
--outdir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/corrected_assembly


















