#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J leono_QUAST
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load quast

# Your commands
cd $SNIC_TMP
python /sw/bioinfo/quast/5.0.2/rackham/bin/quast.py \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/pacbio_assembly/pacbio.contigs.fasta \
-o /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/assembly_quality \
-r /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/reference_assembly/Scaffold_10_reference.fasta











