#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -t 04:00:00
#SBATCH -J leono_STAR
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load star
module load samtools

# Your commands
cd $SNIC_TMP
STAR --runThreadN 16 \
--runMode genomeGenerate \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--genomeFastaFiles /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/Andreas/FilerTillLeo/durian_pilon.fasta.masked \
--sjdbGTFfile /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/code/GeneMark-ET/genemark.gtf \
--genomeSAindexNbases 11

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040094_scaffold_10.1.fastq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040094_scaffold_10.2.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_1/Aril_1_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_1/Aril_1_mapped_Aligned.sortedByCoord.out.bam

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040097_scaffold_10.1.fastq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040097_scaffold_10.2.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_2/Aril_2_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_2/Aril_2_mapped_Aligned.sortedByCoord.out.bam

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/trimmed_data/MusangKing_Aril_3.1.fq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/trimmed_data/MusangKing_Aril_3.2.fq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_3/Aril_3_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Aril_3/Aril_3_mapped_Aligned.sortedByCoord.out.bam

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040092_scaffold_10.1.fastq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040092_scaffold_10.2.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Leaf/Leaf_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Leaf/Leaf_mapped_Aligned.sortedByCoord.out.bam

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040093_scaffold_10.1.fastq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040093_scaffold_10.2.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Root/Root_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Root/Root_mapped_Aligned.sortedByCoord.out.bam

STAR --runThreadN 16 \
--readFilesIn /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040096_scaffold_10.1.fastq.gz /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/data/raw_data/transcriptome/trimmed/SRR6040096_scaffold_10.1.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression \
--outFileNamePrefix /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Stem/Stem_mapped_ \
--outSAMtype BAM SortedByCoordinate \
--limitBAMsortRAM 2292611330 \
--outSAMunmapped Within \
--outSAMattributes Standard

samtools index /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/03_rna_mapping/Mapping_for_differential_expression/Stem/Stem_mapped_Aligned.sortedByCoord.out.bam

