#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 10:00:00
#SBATCH -J leono_RepeatMasker
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4675@student.uu.se
# Load modules
module load bioinfo-tools
module load RepeatMasker

# Your commands
cd $SNIC_TMP
RepeatMasker -species malvids -xsmall \
/home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/analyses/01_genome_assembly/corrected_assembly/Corrected_assembly.fasta
