#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:15:00
#SBATCH -J leono_filemaker
#SBATCH --mail-type=ALL
#SBATCH --mail-user leonora.eriksson.4576@student.uu.se

# Load modules
module load bioinfo-tools
module load braker
module load biopython/1.80-py3.10.8

# Code
cd $SNIC_TMP
getAnnoFastaFromJoingenes.py \
-g /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/code/genome.fa \
-f /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/code/augustus.hints.gtf \
-o /home/leono/GenomeAnalysis_Project/GenomeAnalysisProject/code/Annotated_protein_seq
